# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('response', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiablity', models.BooleanField(default=False)),
                ('location', models.IntegerField()),
                ('chip_work', models.BooleanField(default=False)),
                ('passport', models.BooleanField(default=False)),
                ('passport_available', models.BooleanField(default=False)),
                ('id_using', models.BooleanField(default=False)),
                ('id_verifying', models.BooleanField(default=False)),
                ('id_using_marking', models.BooleanField(default=False)),
                ('markings_correct', models.BooleanField(default=False)),
                ('distinctive_traits', models.BooleanField(default=False)),
                ('owner_sta', models.BooleanField(default=False)),
                ('good_id', models.BooleanField(default=False)),
            ],
        ),
    ]
